
name: 'retail_pipeline'
version: '1.0.0'
config-version: 2

profile: 'retail_snowflake'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by 'dbt clean'
  - "target"
  - "dbt_packages"

models:
  retail_pipeline:
    # Configurar materialización por defecto
    raw:
      +materialized: view
      +schema: RAW
    stage:
      +materialized: view
      +schema: STAGE
    marts:
      +materialized: table
      +schema: ANALYTICS
