AWSTemplateFormatVersion: '2010-09-09'
Description: 'Serverless Retail Data Pipeline: S3, Lambda, SNS, and IAM permissions.'
Parameters:
  ProjectName:
    Type: String
    Default: retail-data-pipeline
    Description: Base name for resources.
  SnowflakeAccount:
    Type: String
    Description: Snowflake Account Locator (e.g., xy12345.us-east-1).
  SnowflakeUser:
    Type: String
    Default: LAMBDA_USER
    Description: User for Lambda to connect to Snowflake.
  SnowflakePassword:
    Type: String
    NoEcho: true
    Description: Password for Snowflake User.
  SnowflakeRole:
    Type: String
    Default: SYSADMIN
    Description: Role for Lambda to use in Snowflake.
  SnowflakeWarehouse:
    Type: String
    Default: COMPUTE_WH
    Description: Warehouse for COPY INTO execution.
  SnowflakeDatabase:
    Type: String
    Default: RETAIL_DB
    Description: Target Database.
Resources:
  DataBucket:
    Type: AWS::S3::Bucket
    DependsOn: LambdaInvokePermission
    Properties:
      BucketName:
        Fn::Sub: ${ProjectName}-${AWS::AccountId}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      NotificationConfiguration:
        LambdaConfigurations:
        - Event: s3:ObjectCreated:*
          Filter:
            S3Key:
              Rules:
              - Name: prefix
                Value: inbox/
          Function:
            Fn::GetAtt:
            - IngestionLambda
            - Arn
  ErrorTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName:
        Fn::Sub: ${ProjectName}-errors
  SnowflakeAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${ProjectName}-snowflake-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS:
              Fn::Sub: arn:aws:iam::${AWS::AccountId}:root
          Action: sts:AssumeRole
      Policies:
      - PolicyName: S3Access
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:GetObject
            - s3:GetObjectVersion
            Resource:
              Fn::Sub: arn:aws:s3:::${ProjectName}-${AWS::AccountId}/*
          - Effect: Allow
            Action:
            - s3:ListBucket
            - s3:GetBucketLocation
            Resource:
              Fn::Sub: arn:aws:s3:::${ProjectName}-${AWS::AccountId}
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${ProjectName}-lambda-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyName: S3Access
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:GetObject
            - s3:PutObject
            - s3:DeleteObject
            Resource:
              Fn::Sub: arn:aws:s3:::${ProjectName}-${AWS::AccountId}/*
      - PolicyName: SNSAccess
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: sns:Publish
            Resource:
              Ref: ErrorTopic
  IngestionLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName:
        Fn::Sub: ${ProjectName}-ingestor
      Handler: app.lambda_handler
      Runtime: python3.9
      Code:
        S3Bucket: retail-data-pipeline-deployments-554074173959
        S3Key: ed417f493b82002ee44bf00729fa29da
      MemorySize: 128
      Timeout: 60
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Layers:
      - Ref: SnowflakeLayer
      Environment:
        Variables:
          SNOWFLAKE_ACCOUNT:
            Ref: SnowflakeAccount
          SNOWFLAKE_USER:
            Ref: SnowflakeUser
          SNOWFLAKE_PASSWORD:
            Ref: SnowflakePassword
          SNOWFLAKE_ROLE:
            Ref: SnowflakeRole
          SNOWFLAKE_WAREHOUSE:
            Ref: SnowflakeWarehouse
          SNOWFLAKE_DATABASE:
            Ref: SnowflakeDatabase
          SNS_TOPIC_ARN:
            Ref: ErrorTopic
          HISTORY_PATH_STORES: history/stores/
          HISTORY_PATH_TRANSACTIONS: history/transactions/
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Fn::GetAtt:
        - IngestionLambda
        - Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn:
        Fn::Sub: arn:aws:s3:::${ProjectName}-${AWS::AccountId}
  SnowflakeLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName:
        Fn::Sub: ${ProjectName}-snowflake-layer
      Description: Snowflake Connector for Python 3.9
      Content:
        S3Bucket: retail-data-pipeline-deployments-554074173959
        S3Key: 1d919c6055e143b1a973d85478e77583
      CompatibleRuntimes:
      - python3.9
Outputs:
  BucketName:
    Description: S3 Bucket Name
    Value:
      Ref: DataBucket
  SnowflakeRoleArn:
    Description: IAM Role ARN for Snowflake Storage Integration
    Value:
      Fn::GetAtt:
      - SnowflakeAccessRole
      - Arn
  SnsTopicArn:
    Description: SNS Topic ARN for Errors
    Value:
      Ref: ErrorTopic
